//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepositoryLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parameter
    {
        public int ParameterId { get; set; }
        public int ScriptId { get; set; }
        public string ParameterName { get; set; }
        public string Type { get; set; }
        public string ParameterTitle { get; set; }
    
        public virtual Script Script { get; set; }
    }
}
