//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepositoryLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Script
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Script()
        {
            this.Parameters = new HashSet<Parameter>();
        }
    
        public int ScriptId { get; set; }
        public int ModuleId { get; set; }
        public int OperationId { get; set; }
        public string Title { get; set; }
        public string Script1 { get; set; }
        public string TableName { get; set; }
    
        public virtual Module Module { get; set; }
        public virtual Operation Operation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Parameter> Parameters { get; set; }
    }
}
