//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepositoryLayer
{
    using System;
    using System.Configuration;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ShipbobInsightsEntities : DbContext
    {
        private static string _connectionString = "name=ShipbobInsightsEntities";
        static ShipbobInsightsEntities()
        {
          //  if (!string.IsNullOrEmpty(System.Environment.GetEnvironmentVariable("AzureFunction")))
            {
                var connectionString = System.Configuration.ConfigurationManager.ConnectionStrings["ShipbobInsightsEntities"].ConnectionString;

                if (!string.IsNullOrEmpty(connectionString))
                {
                    _connectionString = connectionString;
                }
            }
        }
        public ShipbobInsightsEntities()
            : base(_connectionString)
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Module> Modules { get; set; }
        public virtual DbSet<Operation> Operations { get; set; }
        public virtual DbSet<Parameter> Parameters { get; set; }
        public virtual DbSet<Script> Scripts { get; set; }
    }
}
